### ISSUE TITLE
bug/regression: v0.7 breaks Django 1.6 compatibility

### ISSUE THREAD

**Issue by stefanfoulis** [aldryn/aldryn-boilerplates#10]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/async.py", line 45, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/ggevent.py", line 151, in handle_request
    super(GeventWorker, self).handle_request(*args)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/async.py", line 93, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/dj_static.py", line 91, in __call__
    return self.debug_cling(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/handlers.py", line 68, in __call__
    return super(StaticFilesHandler, self).__call__(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 206, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/handlers.py", line 58, in get_response
    return self.serve(request)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/handlers.py", line 51, in serve
    return serve(request, self.file_path(request.path), insecure=True)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/views.py", line 35, in serve
    absolute_path = finders.find(normalized_path)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/finders.py", line 239, in find
    result = finder.find(path, all=all)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/finders.py", line 147, in find
    match = self.find_in_app(app, path)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/finders.py", line 160, in find_in_app
    if storage.prefix:
AttributeError: 'BoilerplateAppStaticStorage' object has no attribute 'prefix'
```

**Comment by razisayyed** [comment]
Please take a look at #9
